### ISSUE TITLE
Fork and clone hyperlink confusing people

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/js-reference-types#23] opened 2016-05-17 15:41 UTC
People are confused by the hyperlink pointing to the 'meta' repo during the 'Fork and clone' this repository, and are forking and cloning the 'meta' repo instead of the THIS repo.

**Comment by jrhorn424** [comment] 2016-05-17 19:15
That's because it's a help article. I'll leave this here so everyone takes note. Feel free to close after two weeks.

**Comment by gaand** [comment] 2016-05-24 02:37
I commented on a related issue on a different repo @payne-chris-r any ideas?  In that issue you suggested a fix.  That issue should be linked to this.

**Comment by payne-chris-r** [comment] 2016-05-24 15:14
Yes. @gaand this issue is related to this: https://github.com/ga-wdi-boston/html-css/issues/18

**Comment by gaand** [comment] 2016-07-11 19:20
@jrhorn424 @payne-chris-r Is this closed by 34a922dd20fad2e3726bd2c2ef04baa7b9adb5be ?

**Comment by jrhorn424** [comment] 2016-07-13 15:27
No @gaand that's the confusing commit. The problem is sometimes people think the link that says "fork and clone" will actually do the forking for them. Instead the suggestion was something like:

```
1. Fork and clone this repository. ([FAQ](blah.com)]
```

See the previously linked discussion. Over there you made the point that this is something that should be maintained over at `talk-template`.

**Comment by gaand** [comment] 2016-07-18 14:56
@jrhorn424 If this is supposed to be fixed in talk-template, then is this an issue on this repo at all?

**Comment by payne-chris-r** [comment] 2016-07-18 17:56
Probably not. It was a recurring issue in the first few weeks of class, so the talk-template is probably the best place for the issue. I just didn't understand templates when I opened this and the other one.

**Comment by payne-chris-r** [comment] 2016-07-18 17:57
I see you've opened it there @gaand. Feel free to close this and the other related one (https://github.com/ga-wdi-boston/html-css/issues/18)

**Closed as completed** 2016-07-18 17:58 UTC
Labels: wontfix
